// Arabic (RTL) - Algeria Localization
export const arStrings = {
  // App
  appName: 'وصالني',

  // Auth
  auth: {
    welcomeBack: 'مرحباً بعودتك',
    riderWelcome: 'مرحباً\nبعودتك',
    continueJourney: 'متابعة',
    phoneNumber: 'رقم الهاتف',
    phoneLocalPlaceholder: '612 345 678',
    invalidPhoneLocal: 'أدخل رقم هاتف جزائري صالح (5 أو 6 أو 7 + 8 أرقام).',
    password: 'كلمة المرور',
    forgotPassword: 'نسيت كلمة المرور؟',
    createAccount: 'إنشاء حساب',
    newToWasselni: 'جديد على وصالني؟',
    otpVerification: 'التحقق من الرمز',
    enterOtp: 'أدخل الرمز المرسل إلى',
    resendCode: 'إعادة إرسال الرمز',
    didntReceiveCode: 'لم تستلم الرمز؟',
    verify: 'تحقق',
    signUp: 'التسجيل',
    fullName: 'الاسم الكامل',
    email: 'البريد الإلكتروني',
    alreadyHaveAccount: 'لديك حساب بالفعل؟',
    login: 'تسجيل الدخول',
    signIn: 'تسجيل الدخول',
    signInToAccess: 'سجّل الدخول للوصول إلى هذا القسم.',
  },

  // Common
  common: {
    continue: 'متابعة',
    cancel: 'إلغاء',
    confirm: 'تأكيد',
    back: 'رجوع',
    next: 'التالي',
    done: 'تم',
    loading: 'جاري التحميل...',
    error: 'خطأ',
    success: 'نجاح',
    retry: 'إعادة المحاولة',
    save: 'حفظ',
    edit: 'تعديل',
    delete: 'حذف',
    close: 'إغلاق',
    search: 'بحث',
    filter: 'تصفية',
    sort: 'ترتيب',
    apply: 'تطبيق',
    clear: 'مسح',
    seeAll: 'عرض الكل',
    more: 'المزيد',
    less: 'أقل',
    yes: 'نعم',
    no: 'لا',
    ok: 'حسناً',
    or: 'أو',
    and: 'و',
    with: 'مع',
  },

  // Home
  home: {
    whereTo: 'إلى أين؟',
    enterDestination: 'أدخل الوجهة',
    currentLocation: 'الموقع الحالي',
    recent: 'حديث',
    suggested: 'مقترح',
    home: 'المنزل',
    work: 'العمل',
    setLocationOnMap: 'تحديد الموقع على الخريطة',
    aroundYou: 'حولك',
    noSavedLocations: 'لا توجد مواقع محفوظة بعد',
    addYourFirst: 'أضف موقعك الأول',
  },

  // Ride
  ride: {
    findingOptimalRoute: 'جاري إيجاد أفضل مسار',
    setRoute: 'حدد مسارك',
    pickupPlaceholder: 'عنوان نقطة الالتقاط',
    dropoffPlaceholder: 'إلى أين؟',
    useCurrentLocation: 'استخدم موقعي الحالي',
    noPlacesFound: 'لم يتم العثور على أماكن',
    pickup: 'نقطة الالتقاط',
    dropoff: 'نقطة الوصول',
    selectRide: 'اختر الرحلة',
    confirm: 'تأكيد',
    estimatedTime: 'الوقت المتوقع',
    distance: 'المسافة',
    price: 'السعر',
    seats: 'مقاعد',
    minAway: 'دقيقة',
    yourDriverIsArriving: 'السائق في طريقه إليك.',
    licensePlate: 'لوحة الترخيص',
    message: 'رسالة',
    callDriver: 'اتصال بالسائق',
    calling: 'جارٍ الاتصال...',
    callFailed: 'تعذّر الاتصال. حاول مجدداً.',
    startChatHint: 'أرسل رسالة لبدء المحادثة',
    sendMessage: 'إرسال رسالة',
    inRideChat: 'دردشة أثناء الرحلة',
    shareTripStatus: 'مشاركة حالة الرحلة',
    onTheWay: 'في الطريق',
    arrivingAt: 'الوصول في',
    contact: 'اتصال',
    safety: 'السلامة',
    cancelRide: 'إلغاء الرحلة',
    searchingTitle: 'جاري البحث عن سائق...',
    searchingSubtitle: 'نربطك بأقرب مركبة متاحة.',
    insufficientWallet: 'رصيد المحفظة غير كافٍ. أضف رصيداً أو ادفع نقداً.',
    bookingFailed: 'تعذر حجز الرحلة. حاول مجدداً.',
    paymentConfirmed: 'تم تأكيد الدفع',
    paymentConfirmedWallet: 'تم خصم المبلغ من محفظتك لهذه الرحلة.',
    routeDeviation: 'تم رصد انحراف عن المسار',
    safetyHarassment: 'تنبيه سلامة لفظي',
    safetyHarassmentDetail: 'رصدت المراقبة الصوتية احتمال تحرش لفظي أثناء الرحلة.',
    safetyHarassmentPromptTitle: 'هل حدث شيء؟',
    safetyHarassmentPromptBody: 'رصدنا احتمال تحرش في السيارة. إن شعرت بعدم الأمان، أبلغ وسنرفق مقطع الصوت. إن كنت بخير، تجاهل هذا التنبيه.',
    safetyImOk: 'أنا بخير',
    safetyReportNow: 'تبليغ عن حادث',
    driverArrived: 'وصل السائق',
    tripInProgress: 'الرحلة قيد التنفيذ',
    tripCompleted: 'اكتملت الرحلة',
    rateYourTrip: 'قيم رحلتك',
    howWasYourRide: 'كيف كانت رحلتك؟',
    submitRating: 'إرسال التقييم',
    skip: 'تخطي',
    tipDriver: 'إكرامية للسائق',
    addTip: 'إضافة إكرامية',
  },

  // Ride Options
  rideOptions: {
    wasselniCore: 'وصالني Go',
    wasselniPremium: 'وصالني بلس',
    wasselniSpace: 'وصالني XL',
    economyDesc: 'رحلة يومية · سيارات عادية',
    plusDesc: 'رحلة مريحة · سيارات أحدث',
    xlDesc: 'مساحة أكبر · حتى 6 مقاعد',
    tripSummary: '{{distance}} كم · ~{{duration}} د',
    loadingPrices: 'جاري حساب الأسعار…',
    driverEta: 'السائق على بعد ~{{eta}}',
    premiumRider: 'بريميوم',
    changePayment: 'تغيير',
    findingOptimalRoute: 'جاري إيجاد أفضل مسار',
    seatsSuffix: 'مقاعد',
    etaAway: 'بعيد',
    cashPayment: 'نقداً',
    walletPayment: 'المحفظة',
  },

  // Wallet
  wallet: {
    title: 'المحفظة',
    balance: 'الرصيد',
    addFunds: 'إضافة رصيد',
    withdraw: 'سحب',
    paymentMethods: 'طرق الدفع',
    recentActivity: 'النشاط الأخير',
    viewAllActivity: 'عرض كل النشاط',
    default: 'افتراضي',
    connected: 'متصل',
    addNewMethod: 'إضافة طريقة جديدة',
    fundsAdded: 'تمت إضافة الرصيد',
    comingSoon: 'المحفظة قريباً',
    loadError: 'فشل تحميل المحفظة',
    topupHint: 'اختر المبلغ للإضافة عبر EDAHABIA أو CIB',
    customAmount: 'أدخل المبلغ',
    minAmount: 'الحد الأدنى للشحن هو 100 دج',
    topupError: 'فشل بدء الدفع. حاول مجدداً.',
    topupSuccess: 'تم استلام الدفع. سيُحدَّث رصيدك قريباً.',
    proceedToPayment: 'المتابعة للدفع',
    securedByChargily: 'مؤمّن بواسطة Chargily Pay',
    poweredBy: 'Chargily Pay',
    noTransactions: 'لا توجد معاملات بعد',
    pending: 'قيد الانتظار',
  },

  // Activity
  activity: {
    title: 'النشاط',
    trips: 'الرحلات',
    deliveries: 'التوصيلات',
    noTripsYet: 'لا توجد رحلات بعد',
    takeYourFirstRide: 'قم برحلتك الأولى',
  },

  savedLocation: {
    title: 'حفظ مكان',
    searchPlaceholder: 'ابحث عن عنوان أو مدينة…',
    mapHint: 'اضغط على الخريطة أو اسحب الدبوس لتحديد الموقع',
    labelName: 'التسمية',
    namePlaceholder: 'مثال: المنزل، العمل',
    labelAddress: 'العنوان',
    save: 'حفظ المكان',
    nameRequired: 'أدخل اسماً لهذا المكان (منزل، عمل…).',
    addressRequired: 'حدد موقعاً على الخريطة أولاً.',
    saveFailed: 'تعذّر حفظ المكان. حاول مجدداً.',
  },

  // Profile
  profile: {
    title: 'الملف الشخصي',
    personalInfo: 'المعلومات الشخصية',
    settings: 'الإعدادات',
    help: 'المساعدة',
    logout: 'تسجيل الخروج',
    editProfile: 'تعديل الملف الشخصي',
    changePassword: 'تغيير كلمة المرور',
    notifications: 'الإشعارات',
    language: 'اللغة',
    english: 'English',
    arabic: 'العربية',
    privacyPolicy: 'سياسة الخصوصية',
    termsOfService: 'شروط الخدمة',
    about: 'حول التطبيق',
    editTitle: 'تعديل الملف الشخصي',
    fullName: 'الاسم الكامل',
    fullNamePlaceholder: 'أدخل اسمك الكامل',
    email: 'البريد الإلكتروني',
    emailPlaceholder: 'أدخل بريدك الإلكتروني',
    phone: 'رقم الهاتف',
    phonePlaceholder: 'أدخل رقم هاتفك',
    changePhoto: 'تغيير الصورة',
    saveFailed: 'فشل حفظ الملف الشخصي. يرجى المحاولة مرة أخرى.',
    nameRequired: 'يرجى إدخال اسمك.',
    photoUpdated: 'تم تحديث صورة الملف الشخصي.',
    photoUploadFailed: 'تعذّر رفع الصورة. حاول مجدداً.',
    photoPermissionDenied: 'اسمح بالوصول إلى الصور لتغيير صورة الملف الشخصي.',
  },

  // Privacy Policy
  privacyPolicy: {
    title: 'سياسة الخصوصية',
    lastUpdated: 'آخر تحديث: يناير 2024',
    intro: 'وصالني ملتزم بحماية خصوصيتك. تشرح هذه السياسة كيف نجمع ونستخدم ونحمي معلوماتك الشخصية.',
    informationWeCollect: 'المعلومات التي نجمعها',
    collectPersonal: '• معلومات شخصية (الاسم، رقم الهاتف، البريد الإلكتروني)',
    collectLocation: '• بيانات الموقع لطلبات الرحلات والتتبع',
    collectPayment: '• معلومات الدفع',
    collectHistory: '• سجل الرحلات والتفضيلات',
    howWeUseInfo: 'كيف نستخدم معلوماتك',
    useServices: '• لتقديم وتحسين خدماتنا',
    usePayments: '• لمعالجة المدفوعات',
    useCommunicate: '• للتواصل معك بشأن رحلاتك',
    useSafety: '• لضمان السلامة والأمان',
    dataSecurity: 'أمان البيانات',
    securityText: 'ننفذ تدابير أمان معيارية في الصناعة لحماية بياناتك. معلوماتك مشفرة ومخزنة بشكل آمن.',
  },

  // Terms of Service
  termsOfService: {
    title: 'شروط الخدمة',
    lastUpdated: 'آخر تحديث: يناير 2024',
    intro: 'باستخدام وصالني، أنت توافق على هذه الشروط. يرجى قراءتها بعناية.',
    acceptance: 'قبول الشروط',
    acceptanceText: 'من خلال الوصول إلى خدمتنا أو استخدامها، أنت توافق على الالتزام بهذه الشروط.',
    userResponsibilities: 'مسؤوليات المستخدم',
    responsibilityText: 'أنت توافق على استخدام خدمتنا بشكل مسؤول ووفقاً للقوانين المعمول بها.',
    paymentTerms: 'شروط الدفع',
    paymentText: 'يتم معالجة الدفع في نهاية كل رحلة. أنت توافق على دفع جميع الرسوم المطبقة.',
    cancellation: 'سياسة الإلغاء',
    cancellationText: 'يمكنك إلغاء رحلتك في أي وقت قبل الاستلام دون رسوم.',
  },

  // Help
  help: {
    title: 'المساعدة والدعم',
    subtitle: 'كيف يمكننا مساعدتك؟',
    faq: 'الأسئلة الشائعة',
    paymentIssues: 'مشاكل الدفع',
    rideIssues: 'مشاكل الرحلة',
    safetyConcerns: 'مخاوف السلامة',
    contactSupport: 'هل تحتاج مساعدة فورية؟',
    callSupport: 'اتصل بالدعم',
  },

  // Driver
  driver: {
    driver: 'السائق',
    rating: 'التقييم',
    trips: 'رحلة',
    yearsDriving: 'سنوات القيادة',
    memberSince: 'عضو منذ',
    vehicle: 'المركبة',
    licensePlate: 'لوحة الترخيص',
  },

  // Currency - Algerian Dinar
  currency: {
    code: 'DZD',
    symbol: 'دج',
  },

  // Notification preferences
  notifications: {
    preferences: 'تفضيلات الإشعارات',
    rides: 'تحديثات الرحلة',
    ridesDesc: 'احصل على إشعارات حول حالة رحلتك',
    promos: 'العروض',
    promosDesc: 'احصل على عروض خاصة وخصومات',
    safety: 'تنبيهات السلامة',
    safetyDesc: 'إشعارات السلامة الحرجة خلال الرحلات',
  },

  // Safety report
  report: {
    title: 'الإبلاغ عن مشكلة',
    subtitle: 'ماذا حدث خلال هذه الرحلة؟',
    descriptionPlaceholder: 'صِف ما حدث...',
    submit: 'إرسال البلاغ',
    submitted: 'تم إرسال البلاغ',
    thankYou: 'شكراً لك. سيقوم فريق السلامة لدينا بمراجعة بلاغك.',
    failed: 'فشل إرسال البلاغ. يرجى المحاولة مرة أخرى.',
    fillRequired: 'يرجى اختيار فئة ووصف المشكلة.',
    audioEvidenceAttached: 'سيتم إرفاق مقطع صوتي من المقصورة بهذا البلاغ.',
    confirmedMlNote: 'أكد الراكب تنبيهاً صوتياً للسلامة أثناء الرحلة.',
    driverOnTrip: 'السائق في هذه الرحلة: {{name}} · {{plate}}',
    categories: {
      verbal_abuse: 'إساءة لفظية',
      physical_threat: 'تهديد جسدي',
      unsafe_driving: 'قيادة غير آمنة',
      wrong_route: 'مسار خاطئ',
      harassment: 'مضايقة',
      other: 'أخرى',
    },
  },

  // Errors
  errors: {
    networkError: 'خطأ في الاتصال بالشبكة',
    somethingWentWrong: 'حدث خطأ ما',
    pleaseTryAgain: 'يرجى المحاولة مرة أخرى',
    invalidPhone: 'رقم هاتف غير صالح',
    invalidOtp: 'رمز تحقق غير صالح',
    locationPermissionDenied: 'تم رفض إذن الموقع',
    locationServiceDisabled: 'خدمة الموقع معطلة',
  },
} as const;

export default arStrings;
