// English (LTR) - Algeria Localization
export const enStrings = {
  // App
  appName: 'Wasselni',

  // Auth
  auth: {
    welcomeBack: 'Welcome Back',
    riderWelcome: 'Welcome\nBack',
    continueJourney: 'Continue',
    phoneNumber: 'Phone Number',
    phoneLocalPlaceholder: '612 345 678',
    invalidPhoneLocal: 'Enter a valid Algerian mobile number (5, 6, or 7 + 8 digits).',
    password: 'Password',
    forgotPassword: 'Forgot Password?',
    createAccount: 'Create Account',
    newToWasselni: 'New to Wasselni?',
    otpVerification: 'OTP Verification',
    enterOtp: 'Enter the code sent to',
    resendCode: 'Resend Code',
    didntReceiveCode: "Didn't receive code?",
    verify: 'Verify',
    signUp: 'Sign Up',
    fullName: 'Full Name',
    gender: 'I am',
    genderFemale: 'Woman',
    genderMale: 'Man',
    genderRequired: 'Please select an option to book women-only rides.',
    email: 'Email',
    alreadyHaveAccount: 'Already have an account?',
    login: 'Login',
    signIn: 'Sign In',
    signInToAccess: 'Sign in to access this section.',
  },

  // Common
  common: {
    continue: 'Continue',
    cancel: 'Cancel',
    confirm: 'Confirm',
    back: 'Back',
    next: 'Next',
    done: 'Done',
    loading: 'Loading...',
    error: 'Error',
    success: 'Success',
    retry: 'Retry',
    save: 'Save',
    edit: 'Edit',
    delete: 'Delete',
    close: 'Close',
    search: 'Search',
    filter: 'Filter',
    sort: 'Sort',
    apply: 'Apply',
    clear: 'Clear',
    seeAll: 'See All',
    more: 'More',
    less: 'Less',
    yes: 'Yes',
    no: 'No',
    ok: 'OK',
    or: 'or',
    and: 'and',
    with: 'with',
  },

  // Home
  home: {
    whereTo: 'Where to?',
    enterDestination: 'Enter destination',
    currentLocation: 'Current Location',
    recent: 'Recent',
    suggested: 'Suggested',
    home: 'Home',
    work: 'Office',
    setLocationOnMap: 'Set location on map',
    aroundYou: 'Around you',
    noSavedLocations: 'No saved locations yet',
    addYourFirst: 'Add your first location',
  },

  // Ride
  ride: {
    findingOptimalRoute: 'Finding optimal route',
    setRoute: 'Set your route',
    pickupPlaceholder: 'Pickup address',
    dropoffPlaceholder: 'Where to?',
    useCurrentLocation: 'Use my current location',
    noPlacesFound: 'No places found',
    pickup: 'Pickup',
    dropoff: 'Dropoff',
    selectRide: 'Select Ride',
    confirm: 'Confirm',
    estimatedTime: 'Estimated Time',
    distance: 'Distance',
    price: 'Price',
    seats: 'seats',
    minAway: 'min away',
    yourDriverIsArriving: 'Your driver is arriving soon.',
    licensePlate: 'License Plate',
    message: 'Message',
    callDriver: 'Call Driver',
    calling: 'Calling...',
    callFailed: 'Could not connect the call. Try again.',
    audioCall: 'Audio',
    videoCall: 'Video',
    incomingCall: 'Incoming call…',
    connectingCall: 'Connecting…',
    connectedCall: 'Connected',
    callEnded: 'Call ended',
    webrtcDevBuildRequired: 'In-app calls need a development build with WebRTC (run: npx expo prebuild). Expo Go does not support this.',
    startChatHint: 'Send a message to start the conversation',
    sendMessage: 'Send message',
    inRideChat: 'In-ride chat',
    shareTripStatus: 'Share Trip Status',
    onTheWay: 'On the way',
    arrivingAt: 'Arriving at',
    contact: 'Contact',
    safety: 'Safety',
    cancelRide: 'Cancel Ride',
    searchingTitle: 'Finding your driver...',
    searchingSubtitle: 'Matching you with the nearest vehicle.',
    insufficientWallet: 'Insufficient wallet balance. Add funds or pay with cash.',
    bookingFailed: 'Could not book ride. Try again.',
    paymentConfirmed: 'Payment confirmed',
    paymentConfirmedWallet: 'Your wallet was charged for this trip.',
    routeDeviation: 'Route change detected',
    safetyHarassment: 'Verbal safety alert',
    safetyHarassmentDetail: 'In-ride audio monitoring flagged a possible harassment incident.',
    safetyHarassmentPromptTitle: 'Did something happen?',
    safetyHarassmentPromptBody: 'We detected possible harassment in the cabin. If you feel unsafe, report it and we will attach the audio clip. If you are OK, dismiss this alert.',
    safetyImOk: "I'm OK",
    safetyReportNow: 'Report incident',
    driverArrived: 'Driver has arrived',
    tripInProgress: 'Trip in progress',
    tripCompleted: 'Trip completed',
    rateYourTrip: 'Rate your trip',
    howWasYourRide: 'How was your ride?',
    submitRating: 'Submit Rating',
    skip: 'Skip',
    tipDriver: 'Tip Driver',
    addTip: 'Add Tip',
  },

  // Ride Options
  rideOptions: {
    wasselniCore: 'Wasselni Go',
    wasselniPremium: 'Wasselni Plus',
    wasselniSpace: 'Wasselni XL',
    economyDesc: 'Everyday ride · standard sedans',
    plusDesc: 'Comfort ride · newer sedans',
    xlDesc: 'Extra space · up to 6 seats',
    tripSummary: '{{distance}} km · ~{{duration}} min',
    loadingPrices: 'Calculating prices…',
    driverEta: 'Driver ~{{eta}} away',
    premiumRider: 'Premium',
    changePayment: 'Change',
    findingOptimalRoute: 'Finding optimal route',
    seatsSuffix: 'seats',
    etaAway: 'away',
    cashPayment: 'Cash',
    walletPayment: 'Wallet',
    womenOnlyTitle: 'Women drivers only',
    womenOnlySub: 'Verified female drivers · for female riders',
  },

  // Wallet
  wallet: {
    title: 'Wallet',
    balance: 'Balance',
    addFunds: 'Add Funds',
    withdraw: 'Withdraw',
    paymentMethods: 'Payment Methods',
    recentActivity: 'Recent Activity',
    viewAllActivity: 'View All Activity',
    default: 'Default',
    connected: 'Connected',
    addNewMethod: 'Add New Method',
    fundsAdded: 'Funds Added',
    comingSoon: 'Wallet coming soon',
    loadError: 'Failed to load wallet',
    topupHint: 'Choose an amount to add via EDAHABIA or CIB',
    customAmount: 'Enter amount',
    minAmount: 'Minimum top-up is 100 DZD',
    topupError: 'Failed to initiate payment. Try again.',
    topupSuccess: 'Payment received. Your balance will update shortly.',
    proceedToPayment: 'Proceed to Payment',
    securedByChargily: 'Secured by Chargily Pay',
    poweredBy: 'Chargily Pay',
    noTransactions: 'No transactions yet',
    pending: 'Pending',
  },

  // Activity
  activity: {
    title: 'Activity',
    trips: 'Trips',
    deliveries: 'Deliveries',
    noTripsYet: 'No trips yet',
    takeYourFirstRide: 'Take your first ride',
  },

  savedLocation: {
    title: 'Save a place',
    searchPlaceholder: 'Search address or city…',
    mapHint: 'Tap the map or drag the pin to set the exact spot',
    labelName: 'Label',
    namePlaceholder: 'e.g. Home, Work, Gym',
    labelAddress: 'Address',
    save: 'Save place',
    nameRequired: 'Give this place a name (Home, Work, etc.).',
    addressRequired: 'Pick a location on the map first.',
    saveFailed: 'Could not save this place. Try again.',
  },

  // Profile
  profile: {
    title: 'Profile',
    personalInfo: 'Personal Information',
    settings: 'Settings',
    help: 'Help',
    logout: 'Logout',
    editProfile: 'Edit Profile',
    changePassword: 'Change Password',
    notifications: 'Notifications',
    language: 'Language',
    english: 'English',
    arabic: 'Arabic',
    privacyPolicy: 'Privacy Policy',
    termsOfService: 'Terms of Service',
    about: 'About',
    editTitle: 'Edit Profile',
    fullName: 'Full Name',
    fullNamePlaceholder: 'Enter your full name',
    email: 'Email',
    emailPlaceholder: 'Enter your email',
    phone: 'Phone Number',
    phonePlaceholder: 'Enter your phone number',
    changePhoto: 'Change Photo',
    saveFailed: 'Failed to save profile. Please try again.',
    nameRequired: 'Please enter your name.',
    photoUpdated: 'Profile photo updated.',
    photoUploadFailed: 'Could not upload photo. Try again.',
    photoPermissionDenied: 'Allow photo library access to change your profile picture.',
  },

  // Privacy Policy
  privacyPolicy: {
    title: 'Privacy Policy',
    lastUpdated: 'Last updated: January 2024',
    intro: 'Wasselni is committed to protecting your privacy. This policy explains how we collect, use, and safeguard your personal information.',
    informationWeCollect: 'Information We Collect',
    collectPersonal: '• Personal information (name, phone number, email)',
    collectLocation: '• Location data for ride requests and tracking',
    collectPayment: '• Payment information',
    collectHistory: '• Ride history and preferences',
    howWeUseInfo: 'How We Use Your Information',
    useServices: '• To provide and improve our services',
    usePayments: '• To process payments',
    useCommunicate: '• To communicate with you about your rides',
    useSafety: '• To ensure safety and security',
    dataSecurity: 'Data Security',
    securityText: 'We implement industry-standard security measures to protect your data. Your information is encrypted and stored securely.',
  },

  // Terms of Service
  termsOfService: {
    title: 'Terms of Service',
    lastUpdated: 'Last updated: January 2024',
    intro: 'By using Wasselni, you agree to these terms. Please read them carefully.',
    acceptance: 'Acceptance of Terms',
    acceptanceText: 'By accessing or using our service, you agree to be bound by these terms.',
    userResponsibilities: 'User Responsibilities',
    responsibilityText: 'You agree to use our service responsibly and in accordance with applicable laws.',
    paymentTerms: 'Payment Terms',
    paymentText: 'Payment is processed at the end of each ride. You agree to pay all applicable fees.',
    cancellation: 'Cancellation Policy',
    cancellationText: 'You may cancel your ride at any time before pickup without charge.',
  },

  // Help
  help: {
    title: 'Help & Support',
    subtitle: 'How can we help you?',
    faq: 'Frequently Asked Questions',
    paymentIssues: 'Payment Issues',
    rideIssues: 'Ride Issues',
    safetyConcerns: 'Safety Concerns',
    contactSupport: 'Need immediate help?',
    callSupport: 'Call Support',
  },

  // Driver
  driver: {
    driver: 'Driver',
    rating: 'Rating',
    trips: 'trips',
    yearsDriving: 'Years Driving',
    memberSince: 'Member Since',
    vehicle: 'Vehicle',
    licensePlate: 'License Plate',
  },

  // Currency - Algerian Dinar
  currency: {
    code: 'DZD',
    symbol: 'DA',
  },

  // Notification preferences
  notifications: {
    preferences: 'Notification Preferences',
    rides: 'Ride Updates',
    ridesDesc: 'Get notified about your ride status',
    promos: 'Promotions',
    promosDesc: 'Receive special offers and discounts',
    safety: 'Safety Alerts',
    safetyDesc: 'Critical safety notifications during rides',
  },

  // Safety report
  report: {
    title: 'Report an Issue',
    subtitle: 'What happened during this trip?',
    descriptionPlaceholder: 'Describe what happened...',
    submit: 'Submit Report',
    submitted: 'Report Submitted',
    thankYou: 'Thank you. Our safety team will review your report.',
    failed: 'Failed to submit report. Please try again.',
    fillRequired: 'Please select a category and describe the issue.',
    audioEvidenceAttached: 'A cabin audio clip will be attached to this report.',
    confirmedMlNote: 'Rider confirmed in-ride audio safety alert.',
    driverOnTrip: 'Driver on this trip: {{name}} · {{plate}}',
    categories: {
      verbal_abuse: 'Verbal Abuse',
      physical_threat: 'Physical Threat',
      unsafe_driving: 'Unsafe Driving',
      wrong_route: 'Wrong Route',
      harassment: 'Harassment',
      other: 'Other',
    },
  },

  // Errors
  errors: {
    networkError: 'Network connection error',
    somethingWentWrong: 'Something went wrong',
    pleaseTryAgain: 'Please try again',
    invalidPhone: 'Invalid phone number',
    invalidOtp: 'Invalid verification code',
    locationPermissionDenied: 'Location permission denied',
    locationServiceDisabled: 'Location service disabled',
  },
} as const;

export default enStrings;
